/// Flutter icons YamsMaster
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YamsMaster
///      fonts:
///       - asset: fonts/YamsMaster.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class YamsMasterIcons {
  YamsMasterIcons._();

  static const _kFontFam = 'YamsMaster';
  static const _kFontPkg = null;

  static const IconData dice =
      IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_five =
      IconData(0xf523, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_four =
      IconData(0xf524, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_one =
      IconData(0xf525, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_six =
      IconData(0xf526, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_three =
      IconData(0xf527, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_two =
      IconData(0xf528, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
